// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPfSu8w3CAJmnlR0_YozkuR2plaovhTD8',
    appId: '1:264763726470:web:78616b53b07e2dec56cf07',
    messagingSenderId: '264763726470',
    projectId: 'reharvest-14f7d',
    authDomain: 'reharvest-14f7d.firebaseapp.com',
    storageBucket: 'reharvest-14f7d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCc-U51Z5b79xGiXC2t94ygqIK6iWrHqYQ',
    appId: '1:264763726470:android:215183bacb71151a56cf07',
    messagingSenderId: '264763726470',
    projectId: 'reharvest-14f7d',
    storageBucket: 'reharvest-14f7d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGGWULm84UOODI3KKHQkS2iphZoqbgSzI',
    appId: '1:264763726470:ios:f6bd84978d1404fd56cf07',
    messagingSenderId: '264763726470',
    projectId: 'reharvest-14f7d',
    storageBucket: 'reharvest-14f7d.firebasestorage.app',
    iosBundleId: 'com.example.reharvest',
  );
}
